from pathlib import Path
import argparse
import pandas as pd


FLOAT_TOLERANCE = 0.0001


def parse_args():
    parser = argparse.ArgumentParser(
        description="Compare Analysis 1 outputs generated by Spark SQL and Spark Core."
    )
    parser.add_argument(
        "--spark-sql-output",
        required=True,
        help="Spark SQL output directory.",
    )
    parser.add_argument(
        "--spark-core-output",
        required=True,
        help="Spark Core output directory.",
    )
    parser.add_argument(
        "--report",
        default="docs/analysis_1_output_comparison.md",
        help="Markdown report path.",
    )
    return parser.parse_args()


def find_single_part_file(output_dir: Path) -> Path:
    part_files = sorted(
        file
        for file in output_dir.iterdir()
        if file.is_file()
        and file.name.startswith("part-")
        and not file.name.endswith(".crc")
    )

    if not part_files:
        raise FileNotFoundError(f"No part file found in {output_dir}")

    if len(part_files) > 1:
        raise ValueError(f"Expected one part file in {output_dir}, found {len(part_files)}")

    return part_files[0]


def normalize_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    expected_columns = [
        "airline",
        "origin",
        "total_flights",
        "min_arr_delay",
        "max_arr_delay",
        "avg_arr_delay",
        "cancelled_flights",
        "cancellation_rate",
        "active_months",
    ]

    df = df[expected_columns].copy()

    df["airline"] = df["airline"].astype(str)
    df["origin"] = df["origin"].astype(str)
    df["active_months"] = df["active_months"].astype(str)

    integer_columns = [
        "total_flights",
        "cancelled_flights",
    ]

    float_columns = [
        "min_arr_delay",
        "max_arr_delay",
        "avg_arr_delay",
        "cancellation_rate",
    ]

    for column in integer_columns:
        df[column] = pd.to_numeric(df[column], errors="coerce").astype("Int64")

    for column in float_columns:
        df[column] = pd.to_numeric(df[column], errors="coerce")

    df = df.sort_values(["airline", "origin"]).reset_index(drop=True)

    return df


def compare_dataframes(left: pd.DataFrame, right: pd.DataFrame) -> tuple[bool, pd.DataFrame]:
    non_float_columns = [
        "airline",
        "origin",
        "total_flights",
        "cancelled_flights",
        "active_months",
    ]

    float_columns = [
        "min_arr_delay",
        "max_arr_delay",
        "avg_arr_delay",
        "cancellation_rate",
    ]

    differences = []

    for column in non_float_columns:
        mismatch_mask = left[column] != right[column]
        for index in left.index[mismatch_mask]:
            differences.append(
                {
                    "row_index": index,
                    "column": column,
                    "spark_sql": left.at[index, column],
                    "spark_core": right.at[index, column],
                    "absolute_difference": "",
                }
            )

    for column in float_columns:
        left_values = left[column]
        right_values = right[column]

        mismatch_mask = (
            (left_values.isna() != right_values.isna())
            | ((left_values - right_values).abs() > FLOAT_TOLERANCE)
        )

        for index in left.index[mismatch_mask]:
            spark_sql_value = left.at[index, column]
            spark_core_value = right.at[index, column]

            if pd.isna(spark_sql_value) or pd.isna(spark_core_value):
                absolute_difference = ""
            else:
                absolute_difference = abs(spark_sql_value - spark_core_value)

            differences.append(
                {
                    "row_index": index,
                    "column": column,
                    "spark_sql": spark_sql_value,
                    "spark_core": spark_core_value,
                    "absolute_difference": absolute_difference,
                }
            )

    differences_df = pd.DataFrame(differences)

    return differences_df.empty, differences_df


def main() -> None:
    args = parse_args()

    spark_sql_output_dir = Path(args.spark_sql_output)
    spark_core_output_dir = Path(args.spark_core_output)
    report_path = Path(args.report)

    spark_sql_file = find_single_part_file(spark_sql_output_dir)
    spark_core_file = find_single_part_file(spark_core_output_dir)

    spark_sql_df = normalize_dataframe(pd.read_csv(spark_sql_file))
    spark_core_df = normalize_dataframe(pd.read_csv(spark_core_file))

    same_shape = spark_sql_df.shape == spark_core_df.shape
    same_columns = list(spark_sql_df.columns) == list(spark_core_df.columns)

    if same_shape and same_columns:
        values_match, differences = compare_dataframes(spark_sql_df, spark_core_df)
    else:
        values_match = False
        differences = pd.DataFrame()

    outputs_match = same_shape and same_columns and values_match

    report_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Analysis 1 Output Comparison",
        "",
        "## Compared outputs",
        "",
        f"- Spark SQL output: `{spark_sql_file}`",
        f"- Spark Core output: `{spark_core_file}`",
        "",
        "## Comparison policy",
        "",
        f"- Floating point tolerance: **{FLOAT_TOLERANCE}**",
        "",
        "## Result",
        "",
        f"- Same shape: **{same_shape}**",
        f"- Same columns: **{same_columns}**",
        f"- Outputs match within tolerance: **{outputs_match}**",
        "",
        "## Shape",
        "",
        f"- Spark SQL rows: **{len(spark_sql_df):,}**",
        f"- Spark Core rows: **{len(spark_core_df):,}**",
        f"- Columns: **{len(spark_sql_df.columns)}**",
        "",
    ]

    if differences.empty:
        lines.extend(
            [
                "## Differences",
                "",
                "No differences found beyond the configured tolerance.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "## Differences",
                "",
                "Differences were found beyond the configured tolerance. Showing the first rows:",
                "",
                differences.head(30).to_markdown(index=False),
                "",
            ]
        )

    report_path.write_text("\n".join(lines), encoding="utf-8")

    print("Analysis 1 output comparison completed.")
    print(f"Spark SQL file: {spark_sql_file}")
    print(f"Spark Core file: {spark_core_file}")
    print(f"Floating point tolerance: {FLOAT_TOLERANCE}")
    print(f"Outputs match within tolerance: {outputs_match}")
    print(f"Report saved to: {report_path}")

    if not outputs_match:
        raise SystemExit(1)


if __name__ == "__main__":
    main()