from pathlib import Path
import argparse
import pandas as pd


FLOAT_TOLERANCE = 0.0002


def parse_args():
    parser = argparse.ArgumentParser(
        description="Compare Analysis 1 outputs generated by Hive and Spark SQL."
    )
    parser.add_argument(
        "--spark-sql-output",
        required=True,
        help="Spark SQL output directory.",
    )
    parser.add_argument(
        "--hive-output",
        required=True,
        help="Hive output directory.",
    )
    parser.add_argument(
        "--report",
        default="docs/analysis_1_hive_spark_sql_comparison.md",
        help="Markdown report path.",
    )
    return parser.parse_args()


def find_spark_part_file(output_dir: Path) -> Path:
    part_files = sorted(
        file
        for file in output_dir.iterdir()
        if file.is_file()
        and file.name.startswith("part-")
        and not file.name.endswith(".crc")
    )

    if len(part_files) != 1:
        raise ValueError(f"Expected one Spark part file in {output_dir}, found {len(part_files)}")

    return part_files[0]


def find_hive_output_file(output_dir: Path) -> Path:
    files = sorted(
        file
        for file in output_dir.iterdir()
        if file.is_file()
        and not file.name.startswith(".")
        and not file.name.endswith(".crc")
    )

    if len(files) != 1:
        raise ValueError(f"Expected one Hive output file in {output_dir}, found {len(files)}")

    return files[0]


def normalize_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    expected_columns = [
        "airline",
        "origin",
        "total_flights",
        "min_arr_delay",
        "max_arr_delay",
        "avg_arr_delay",
        "cancelled_flights",
        "cancellation_rate",
        "active_months",
    ]

    df = df[expected_columns].copy()

    df["airline"] = df["airline"].astype(str)
    df["origin"] = df["origin"].astype(str)
    df["active_months"] = df["active_months"].astype(str)

    df["total_flights"] = pd.to_numeric(df["total_flights"], errors="coerce").astype("Int64")
    df["cancelled_flights"] = pd.to_numeric(df["cancelled_flights"], errors="coerce").astype("Int64")

    for column in ["min_arr_delay", "max_arr_delay", "avg_arr_delay", "cancellation_rate"]:
        df[column] = pd.to_numeric(df[column], errors="coerce")

    return df.sort_values(["airline", "origin"]).reset_index(drop=True)


def compare_dataframes(left: pd.DataFrame, right: pd.DataFrame) -> tuple[bool, pd.DataFrame]:
    non_float_columns = [
        "airline",
        "origin",
        "total_flights",
        "cancelled_flights",
        "active_months",
    ]

    float_columns = [
        "min_arr_delay",
        "max_arr_delay",
        "avg_arr_delay",
        "cancellation_rate",
    ]

    differences = []

    for column in non_float_columns:
        mismatch_mask = left[column] != right[column]
        for index in left.index[mismatch_mask]:
            differences.append(
                {
                    "row_index": index,
                    "column": column,
                    "spark_sql": left.at[index, column],
                    "hive": right.at[index, column],
                    "absolute_difference": "",
                }
            )

    for column in float_columns:
        left_values = left[column]
        right_values = right[column]

        mismatch_mask = (
            (left_values.isna() != right_values.isna())
            | ((left_values - right_values).abs() > FLOAT_TOLERANCE)
        )

        for index in left.index[mismatch_mask]:
            spark_sql_value = left.at[index, column]
            hive_value = right.at[index, column]

            if pd.isna(spark_sql_value) or pd.isna(hive_value):
                absolute_difference = ""
            else:
                absolute_difference = abs(spark_sql_value - hive_value)

            differences.append(
                {
                    "row_index": index,
                    "column": column,
                    "spark_sql": spark_sql_value,
                    "hive": hive_value,
                    "absolute_difference": absolute_difference,
                }
            )

    differences_df = pd.DataFrame(differences)

    return differences_df.empty, differences_df


def main() -> None:
    args = parse_args()

    spark_sql_file = find_spark_part_file(Path(args.spark_sql_output))
    hive_file = find_hive_output_file(Path(args.hive_output))

    spark_sql_df = normalize_dataframe(pd.read_csv(spark_sql_file))

    hive_df = pd.read_csv(
        hive_file,
        header=None,
        names=[
            "airline",
            "origin",
            "total_flights",
            "min_arr_delay",
            "max_arr_delay",
            "avg_arr_delay",
            "cancelled_flights",
            "cancellation_rate",
            "active_months",
        ],
    )
    hive_df = normalize_dataframe(hive_df)

    same_shape = spark_sql_df.shape == hive_df.shape
    same_columns = list(spark_sql_df.columns) == list(hive_df.columns)

    if same_shape and same_columns:
        values_match, differences = compare_dataframes(spark_sql_df, hive_df)
    else:
        values_match = False
        differences = pd.DataFrame()

    outputs_match = same_shape and same_columns and values_match

    report_path = Path(args.report)
    report_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Analysis 1 Hive vs Spark SQL Comparison",
        "",
        "## Compared outputs",
        "",
        f"- Spark SQL output: `{spark_sql_file}`",
        f"- Hive output: `{hive_file}`",
        "",
        "## Comparison policy",
        "",
        f"- Floating point tolerance: **{FLOAT_TOLERANCE}**",
        "",
        "## Result",
        "",
        f"- Same shape: **{same_shape}**",
        f"- Same columns: **{same_columns}**",
        f"- Outputs match within tolerance: **{outputs_match}**",
        "",
        "## Shape",
        "",
        f"- Spark SQL rows: **{len(spark_sql_df):,}**",
        f"- Hive rows: **{len(hive_df):,}**",
        f"- Columns: **{len(spark_sql_df.columns)}**",
        "",
    ]

    if differences.empty:
        lines.extend(
            [
                "## Differences",
                "",
                "No differences found beyond the configured tolerance.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "## Differences",
                "",
                "Differences were found beyond the configured tolerance. Showing the first rows:",
                "",
                differences.head(30).to_markdown(index=False),
                "",
            ]
        )

    report_path.write_text("\n".join(lines), encoding="utf-8")

    print("Analysis 1 Hive vs Spark SQL comparison completed.")
    print(f"Spark SQL file: {spark_sql_file}")
    print(f"Hive file: {hive_file}")
    print(f"Floating point tolerance: {FLOAT_TOLERANCE}")
    print(f"Outputs match within tolerance: {outputs_match}")
    print(f"Report saved to: {report_path}")

    if not outputs_match:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
